/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SimulatorRouteImport } from './routes/simulator'
import { Route as InvestorRouteImport } from './routes/investor'
import { Route as IndexRouteImport } from './routes/index'
import { Route as InvestorThreadIdRouteImport } from './routes/investor.$threadId'

const SimulatorRoute = SimulatorRouteImport.update({
  id: '/simulator',
  path: '/simulator',
  getParentRoute: () => rootRouteImport,
} as any)
const InvestorRoute = InvestorRouteImport.update({
  id: '/investor',
  path: '/investor',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const InvestorThreadIdRoute = InvestorThreadIdRouteImport.update({
  id: '/$threadId',
  path: '/$threadId',
  getParentRoute: () => InvestorRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/investor': typeof InvestorRouteWithChildren
  '/simulator': typeof SimulatorRoute
  '/investor/$threadId': typeof InvestorThreadIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/investor': typeof InvestorRouteWithChildren
  '/simulator': typeof SimulatorRoute
  '/investor/$threadId': typeof InvestorThreadIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/investor': typeof InvestorRouteWithChildren
  '/simulator': typeof SimulatorRoute
  '/investor/$threadId': typeof InvestorThreadIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/investor' | '/simulator' | '/investor/$threadId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/investor' | '/simulator' | '/investor/$threadId'
  id: '__root__' | '/' | '/investor' | '/simulator' | '/investor/$threadId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  InvestorRoute: typeof InvestorRouteWithChildren
  SimulatorRoute: typeof SimulatorRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/simulator': {
      id: '/simulator'
      path: '/simulator'
      fullPath: '/simulator'
      preLoaderRoute: typeof SimulatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/investor': {
      id: '/investor'
      path: '/investor'
      fullPath: '/investor'
      preLoaderRoute: typeof InvestorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/investor/$threadId': {
      id: '/investor/$threadId'
      path: '/$threadId'
      fullPath: '/investor/$threadId'
      preLoaderRoute: typeof InvestorThreadIdRouteImport
      parentRoute: typeof InvestorRoute
    }
  }
}

interface InvestorRouteChildren {
  InvestorThreadIdRoute: typeof InvestorThreadIdRoute
}

const InvestorRouteChildren: InvestorRouteChildren = {
  InvestorThreadIdRoute: InvestorThreadIdRoute,
}

const InvestorRouteWithChildren = InvestorRoute._addFileChildren(
  InvestorRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  InvestorRoute: InvestorRouteWithChildren,
  SimulatorRoute: SimulatorRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
